version = 0.1
[default.deploy.parameters]
stack_name = "python-test"
resolve_s3 = true
s3_prefix = "python-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "vpc=\"vpc-0c1fc870a129397db\" InstanceSubnetID=\"subnet-053fe60d3d797a743\" Environment=\"staging\" InstanceType=\"t2.medium\" loadbalancer=\"subnet-053fe60d3d797a743\" loadbalancerVisibility=\"public\" SolutionStack=\"64bit Amazon Linux 2023 v4.0.4 running Python 3.11\" BucketName=\"python-test-elb\" BucketFileName=\"python.zip\""
image_repositories = []
